apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-backend
  namespace: default
  annotations:
    # Replace with the output value from terraform:
    # terraform output app_workload_role_arn
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/fintech-secure-dev-app-workload-role
